apiVersion: helm.toolkit.fluxcd.io/v2beta1  
kind: HelmRelease  
metadata:  
  name: v2-deploy-test
  namespace: arc-v2-runners-scaleset
spec:  
  interval: 5m  
  chart:  
    spec:  
      chart: gha-runner-scale-set  
      version: "0.14.1"  
      sourceRef:  
        kind: HelmRepository  
        name: arc-charts-v2 
        namespace: flux-system  
  install:
    createNamespace: true        
  values:  
    githubConfigUrl: https://github.com/bhaskar-areti
    githubConfigSecret: arc-github-app-v2
    minRunners: 1  
    maxRunners: 5  
#https://github.com/actions/actions-runner-controller/blob/5f4c132f/charts/gha-runner-scale-set/Chart.yaml
    #  Dedicated scale set identity
    runnerScaleSetName: v2-deploy-test
#    runnerGroup: v2-test-group
    labels:
      - v2-deploy-test
    runner:
      image:
        repository: ghcr.io/actions/actions-runner
        tag: latest