apiVersion: helm.toolkit.fluxcd.io/v2beta1  
kind: HelmRelease  
metadata:  
  name: github-runners-v2-scaleset
  namespace: arc-v2-runners-scaleset
spec:  
  interval: 5m  
  chart:  
    spec:  
      chart: gha-runner-scale-set  
      version: "0.14.1"  
      sourceRef:  
        kind: HelmRepository  
        name: arc-charts-v2 
        namespace: flux-system  
  install:
    createNamespace: true        
  values:  
    githubConfigUrl: https://github.com/bhaskar-areti/test-githubactions-como-pricer
    githubConfigSecret: arc-github-app-v2
    minRunners: 1  
    maxRunners: 5  
    controllerServiceAccount:  
      name: "gha-runner-scale-set-controller-gha-rs-controller"  
      namespace: "arc-v2-runners-scaleset"
#https://github.com/actions/actions-runner-controller/blob/5f4c132f/charts/gha-runner-scale-set/Chart.yaml
    #  Dedicated scale set identity
    runnerScaleSetName: v2-deploy-test
    runnerGroup: v2-test-group
    labels:
      - arc-v2
      - deploy
      - linux
    runner:
      image:
        repository: ghcr.io/actions/actions-runner
        tag: latest
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "2"
          memory: "4Gi"
      