#https://github.com/actions-runner-controller/actions-runner-controller
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: test-pda-api-runner
  namespace: default
spec:
  replicas: 1
  template:
    # metadata:
    #   annotations:
    #     sidecar.istio.io/inject: "false"
    spec:
      image: summerwind/actions-runner-dind:v2.333.0-ubuntu-24.04-5f4c132
      # dockerdWithinRunnerContainer: true
      repository: bhaskar-areti/Istio-helm-migration
      labels:
        - refs/heads/main
        - como-app
