apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-helm #updated to istio-helm from istio
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/istio_1.24.5
  prune: true
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: istio-ingressgateway
          namespace: flux-system
        spec:
          values:
            service:
              externalIPs:
                # The unique IPs for the 'rc' cluster
                - 10.2.101.161
                - 10.2.101.162
                - 10.2.101.163
            labels:
              # Adding Static network label is added back to the deployment via patch
              topology.istio.io/network: network-app
            podAnnotations:
              # Adding Static network annotation is added back to the proxy metadata via patch
              "sidecar.istio.io/proxyMetadata": |
                ISTIO_META_ROUTER_MODE: "sni-dnat"
                ISTIO_META_REQUESTED_NETWORK_VIEW: network-app
      target:
        kind: HelmRelease
        name: istio-ingressgateway
