---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: flux-system # Or your desired gateway namespace
spec:
  interval: 5m
  timeout: 10m
  releaseName: istio-ingressgateway # Added releaseName for clarity/consistency
  targetNamespace: istio-system  
  chart:
    spec:
      chart: gateway
      version: 1.24.5
      sourceRef:
        kind: HelmRepository
        name: istio-helmrepo
        namespace: flux-system
  dependsOn:
    - name: istiod
      namespace: flux-system
    - name: istio-base
      namespace: flux-system      
  values:
    replicaCount: 2 
    global:
      proxy:
        privileged: true
    # default: 
    #   image: registry.k8s.io/istio/proxyv2:1.24.5        
    # # 1. Ensure the workload labels match our Istio Gateway CRs (this is the default, but good to check)
    # # labels:
    # #   istio: ingressgateway
    # #   app: istio-ingressgateway
    # #   # topology.istio.io/network: network-app # Add this if it's required for our topology
    # #   # 2. Replicate the custom Service Type and ExternalIPs
    # service:
    #   type: NodePort # CRITICAL: Change from default LoadBalancer
    #   externalIPs:
    #     - 10.2.101.161
    #     - 10.2.101.162
    #     - 10.2.101.163
    #   # 3. Replicate all custom ports with their NodePort values
    #   ports:
    #     - name: status-port
    #       port: 15021
    #       targetPort: 15021
    #     - name: http2
    #       port: 80
    #       targetPort: 8080 # CRITICAL: Old targetPort was 8080
    #       nodePort: 30080 # CRITICAL: Replicate old NodePort
    #     - name: https
    #       port: 443
    #       targetPort: 8443 # CRITICAL: Old targetPort was 8443
    #       nodePort: 30443 # CRITICAL: Replicate old NodePort
    #     - name: postgres
    #       port: 5432
    #       targetPort: 5432
    #       nodePort: 30432 # CRITICAL: Replicate old NodePort
    #     - name: http-grpc
    #       port: 20443
    #       targetPort: 20443
    #       nodePort: 31443 # CRITICAL: Replicate old NodePort
    #     # The following ports may be implicitly handled by the Service created by Istiod,
    #     # but if they were explicitly defined here, include them:
    #     # - name: tls
    #     #   port: 15443
    #     #   targetPort: 15443
    #     # - name: tls-istiod
    #     #   port: 15012
    #     #   targetPort: 15012
    #     # - name: tls-webhook
    #     #   port: 15017
    #     #   targetPort: 15017       
    # # 4. Replicate custom environment variables
    # podAnnotations:
    #   # Optional: if you need to set pod annotations for prometheus scraping, etc.
    #   "sidecar.istio.io/proxyMetadata": |
    #     ISTIO_META_ROUTER_MODE: "sni-dnat"
    #     ISTIO_META_REQUESTED_NETWORK_VIEW: network-app    
# ref: https://github.com/istio/istio/blob/0fb9e6f274272cc77d0d5a49d6ed1ff10edc7b20/manifests/charts/gateway/Chart.yaml