apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  interval: 10m
  releaseName: istiod
  targetNamespace: istio-system
  chart:
    spec:
      chart: istiod
      version: 1.24.5
      sourceRef:
        kind: HelmRepository
        name: istio-helmrepo
        namespace: flux-system
  dependsOn:
    - name: istio-base
      namespace: flux-system 
  values:
#    revision: v124   #When running a single Istio version, use the default revision.
    meshConfig:
      defaultConfig:   
        holdApplicationUntilProxyStarts: true #https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/
    global:
      meshID: mesh1
      multiCluster:
        clusterName: cluster-app
      # Sets the default network for Istiod to reference configuration for:
      network: network-app 
    telemetry:
      enabled: false 
    pilot:
      env:
        PILOT_HTTP10: 1 #This setting is to enable PILOT_HTTP/1.0 support for the Envoy proxies managed by Istio.
#The main purpose of this setting is to ensure backward compatibility in your service mesh
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi

