---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-egressgateway
  namespace: flux-system # Or your desired gateway namespace
spec:
  interval: 5m
  timeout: 15m
  releaseName: istio-egressgateway # Added releaseName for clarity/consistency
  targetNamespace: istio-system  
  chart:
    spec:
      chart: gateway
      version: 1.25.5
      sourceRef:
        kind: HelmRepository
        name: istio-helmrepo
        namespace: flux-system
  dependsOn:
    - name: istiod
      namespace: flux-system
    - name: istio-base
      namespace: flux-system      
  values:
    # components:
    #   ingressGateways:
    #     - name: istio-ingressgateway
    #       enabled: false
    #   egressGateways:
    #     - name: istio-egressgateway
    #       enabled: true 
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1024Mi
    global:
      proxy:
        # resources:
        #   requests:
        #     cpu: 50m
        #     memory: 64Mi
        #   limits:
        #     cpu: 2000m
        #     memory: 1024Mi        
    name: istio-egressgateway
    replicaCount: 1
#    revision: v124
    labels:
      app: istio-egressgateway
      istio: egressgateway
    podAnnotations:
      # important: Triggers the v124 control plane's webhook for processing this pod.
      istio.io/rev: default    
      "sidecar.istio.io/proxyMetadata": |
        ISTIO_META_ROUTER_MODE: "sni-dnat"
        ISTIO_META_REQUESTED_NETWORK_VIEW: network-app         