# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: istiod
#   namespace: flux-system
# spec:
#   interval: 10m
#   releaseName: istiod
#   targetNamespace: istio-system
#   chart:
#     spec:
#       chart: base
#       version: 1.24.5
#       sourceRef:
#         kind: HelmRepository
#         name: istio
#         namespace: flux-system
#   values:
#     global:
#       istioNamespace: istio-system
#     pilot:
#       enabled: true
